"""
Odds API.io Constants
"""

ODDS_API_PROVIDER_NAME = "odds_api"
ODDS_API_PROVIDER_CODE = "oapi"

DEFAULT_BASE_URL = "https://api.odds-api.io/v3"
DEFAULT_SPORT = "football"
SUPPORTED_BOOKMAKERS = ("Bet365", "Unibet")

DEFAULT_TIMEOUT_SECONDS = 10.0
DEFAULT_RETRY_LIMIT = 2
DEFAULT_RATE_LIMIT_PER_SEC = 2.0
DEFAULT_CACHE_TTL_SECONDS = 300
