[build]
  publish = "web"

[[redirects]]
  from = "/api/*"
  to = "https://zielonebety.tailaa37bc.ts.net/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://zielonebety.tailaa37bc.ts.net/health"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
