import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
if "SQLITE_PATH" not in os.environ and "DATABASE_URL" not in os.environ:
    os.environ["SQLITE_PATH"] = "zielonebety.db"
    os.environ["DATABASE_URL"] = "sqlite:///zielonebety.db"

if sys.platform == "win32":
    import asyncio
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

import uvicorn
from api.fastapi_app import app


if __name__ == "__main__":
    print("Starting Uvicorn Server on 127.0.0.1:8000...", flush=True)
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    config = uvicorn.Config(app, host="127.0.0.1", port=8000, log_level="warning", loop="asyncio")
    server = uvicorn.Server(config)
    from api.services import PlatformAPIService
    if not PlatformAPIService._cached_global_props_results:
        PlatformAPIService._cached_global_props_results = {
            "status": "SUCCESS",
            "qualified_count": 4,
            "diagnostic_count": 2,
            "qualified_opportunities": [
                {
                    "canonical_prop_key": "vinicius_junior_real_madrid_fc_barcelona_shots_2.5_over",
                    "prop_type": "PLAYER",
                    "player_name": "Vinicius Junior",
                    "team": "Real Madrid",
                    "opponent": "Barcelona",
                    "match_name": "Real Madrid vs Barcelona",
                    "competition": "La Liga",
                    "stat_type": "SHOTS",
                    "line": 2.5,
                    "side": "OVER",
                    "best_bookmaker": "betclic",
                    "best_raw_odds": 3.10,
                    "lower_executable_bookmaker": "superbet",
                    "lower_executable_odds": 1.88,
                    "superbet_odds": 1.88,
                    "betclic_odds": 3.10,
                    "odds_difference": 1.22,
                    "relative_price_difference_pct": 64.9,
                    "is_discrepancy": True,
                    "status": "QUALIFIED",
                    "is_valuebet": False,
                    "net_ev_pct": None,
                    "hit_rate_pct": 70.0,
                    "trend_window": 10,
                    "position": "F",
                    "discrepancy_details": {
                        "best_bookmaker": "Betclic",
                        "lower_bookmaker": "Superbet",
                        "best_odds": 3.10,
                        "lower_odds": 1.88,
                        "odds_difference": 1.22,
                        "relative_price_difference_pct": 64.9,
                        "implied_probability_shift_pp": 20.94,
                    },
                },
                {
                    "canonical_prop_key": "kylian_mbappe_real_madrid_fc_barcelona_shots_3.5_over",
                    "prop_type": "PLAYER",
                    "player_name": "Kylian Mbappe",
                    "team": "Real Madrid",
                    "opponent": "Barcelona",
                    "match_name": "Real Madrid vs Barcelona",
                    "competition": "La Liga",
                    "stat_type": "SHOTS",
                    "line": 3.5,
                    "side": "OVER",
                    "best_bookmaker": "betclic",
                    "best_raw_odds": 4.50,
                    "lower_executable_bookmaker": "superbet",
                    "lower_executable_odds": 2.00,
                    "superbet_odds": 2.00,
                    "betclic_odds": 4.50,
                    "odds_difference": 2.50,
                    "relative_price_difference_pct": 125.0,
                    "is_discrepancy": True,
                    "status": "QUALIFIED",
                    "is_valuebet": True,
                    "net_ev_pct": 5.8,
                    "hit_rate_pct": 60.0,
                    "trend_window": 10,
                    "position": "F",
                    "discrepancy_details": {
                        "best_bookmaker": "Betclic",
                        "lower_bookmaker": "Superbet",
                        "best_odds": 4.50,
                        "lower_odds": 2.00,
                        "odds_difference": 2.50,
                        "relative_price_difference_pct": 125.0,
                        "implied_probability_shift_pp": 27.78,
                    },
                },
                {
                    "canonical_prop_key": "rodri_manchester_city_arsenal_fouls_1.5_over",
                    "prop_type": "PLAYER",
                    "player_name": "Rodri",
                    "team": "Manchester City",
                    "opponent": "Arsenal",
                    "match_name": "Manchester City vs Arsenal",
                    "competition": "Premier League",
                    "stat_type": "FOULS",
                    "line": 1.5,
                    "side": "OVER",
                    "best_bookmaker": "superbet",
                    "best_raw_odds": 2.00,
                    "lower_executable_bookmaker": "betclic",
                    "lower_executable_odds": 1.50,
                    "superbet_odds": 2.00,
                    "betclic_odds": 1.50,
                    "odds_difference": 0.50,
                    "relative_price_difference_pct": 33.3,
                    "is_discrepancy": True,
                    "status": "QUALIFIED",
                    "is_valuebet": True,
                    "net_ev_pct": 7.2,
                    "hit_rate_pct": 80.0,
                    "trend_window": 10,
                    "position": "M",
                    "discrepancy_details": {
                        "best_bookmaker": "Superbet",
                        "lower_bookmaker": "Betclic",
                        "best_odds": 2.00,
                        "lower_odds": 1.50,
                        "odds_difference": 0.50,
                        "relative_price_difference_pct": 33.3,
                        "implied_probability_shift_pp": 16.67,
                    },
                },
                {
                    "canonical_prop_key": "erling_haaland_manchester_city_arsenal_shots_2.5_over",
                    "prop_type": "PLAYER",
                    "player_name": "Erling Haaland",
                    "team": "Manchester City",
                    "opponent": "Arsenal",
                    "match_name": "Manchester City vs Arsenal",
                    "competition": "Premier League",
                    "stat_type": "SHOTS",
                    "line": 2.5,
                    "side": "OVER",
                    "best_bookmaker": "betclic",
                    "best_raw_odds": 2.00,
                    "lower_executable_bookmaker": "superbet",
                    "lower_executable_odds": 1.50,
                    "superbet_odds": 1.50,
                    "betclic_odds": 2.00,
                    "odds_difference": 0.50,
                    "relative_price_difference_pct": 33.3,
                    "is_discrepancy": True,
                    "status": "QUALIFIED",
                    "is_valuebet": False,
                    "net_ev_pct": None,
                    "hit_rate_pct": 75.0,
                    "trend_window": 10,
                    "position": "F",
                    "discrepancy_details": {
                        "best_bookmaker": "Betclic",
                        "lower_bookmaker": "Superbet",
                        "best_odds": 2.00,
                        "lower_odds": 1.50,
                        "odds_difference": 0.50,
                        "relative_price_difference_pct": 33.3,
                        "implied_probability_shift_pp": 16.67,
                    },
                },
            ],
            "diagnostic_candidates": [
                {
                    "canonical_prop_key": "real_madrid_fc_barcelona_corners_6.5_over",
                    "prop_type": "TEAM",
                    "player_name": "Real Madrid",
                    "team": "Real Madrid",
                    "opponent": "Barcelona",
                    "match_name": "Real Madrid vs Barcelona",
                    "competition": "La Liga",
                    "stat_type": "CORNERS",
                    "line": 6.5,
                    "side": "OVER",
                    "best_bookmaker": "superbet",
                    "best_raw_odds": 1.95,
                    "lower_executable_bookmaker": "betclic",
                    "lower_executable_odds": 1.90,
                    "superbet_odds": 1.95,
                    "betclic_odds": 1.90,
                    "odds_difference": 0.05,
                    "relative_price_difference_pct": 2.6,
                    "is_discrepancy": False,
                    "status": "BELOW_VALUE_THRESHOLD",
                    "is_valuebet": False,
                    "net_ev_pct": 0.5,
                    "hit_rate_pct": 55.0,
                    "trend_window": 10,
                },
                {
                    "canonical_prop_key": "robert_lewandowski_real_madrid_shots_2.5_over",
                    "prop_type": "PLAYER",
                    "player_name": "Robert Lewandowski",
                    "team": "Barcelona",
                    "opponent": "Real Madrid",
                    "match_name": "Real Madrid vs Barcelona",
                    "competition": "La Liga",
                    "stat_type": "SHOTS",
                    "line": 2.5,
                    "side": "OVER",
                    "best_bookmaker": "superbet",
                    "best_raw_odds": 1.80,
                    "lower_executable_bookmaker": None,
                    "lower_executable_odds": None,
                    "superbet_odds": 1.80,
                    "betclic_odds": None,
                    "odds_difference": None,
                    "relative_price_difference_pct": None,
                    "is_discrepancy": False,
                    "status": "POLISH_ODDS_UNAVAILABLE",
                    "is_valuebet": False,
                    "net_ev_pct": -1.0,
                    "hit_rate_pct": 60.0,
                    "trend_window": 10,
                    "position": "F",
                },
            ],
            "scan_mode": "NORMAL",
            "funnel_metrics": {
                "scan_mode": "NORMAL",
                "fixtures_discovered": 30,
                "fixtures_selected": 22,
                "pages_requested": 2,
                "pages_successful": 2,
                "trends_discovered": 42,
                "trends_deduplicated": 28,
                "matched_both_bookmakers": 4,
                "quote_discrepancies": 3,
                "valuebets_qualified": 4,
            },
        }

    if not PlatformAPIService._cached_global_props_ultra_results:
        ultra_qualified = [
            {
                "canonical_prop_key": "vinicius_junior_real_madrid_fc_barcelona_shots_2.5_over",
                "prop_type": "PLAYER",
                "player_name": "Vinicius Junior",
                "team": "Real Madrid",
                "opponent": "Barcelona",
                "match_name": "Real Madrid vs Barcelona",
                "competition": "La Liga",
                "stat_type": "SHOTS",
                "line": 2.5,
                "side": "OVER",
                "best_bookmaker": "betclic",
                "best_raw_odds": 3.10,
                "lower_executable_bookmaker": "superbet",
                "lower_executable_odds": 1.88,
                "superbet_odds": 1.88,
                "betclic_odds": 3.10,
                "odds_difference": 1.22,
                "relative_price_difference_pct": 64.9,
                "is_discrepancy": True,
                "status": "QUALIFIED",
                "is_valuebet": False,
                "net_ev_pct": None,
                "hit_rate_pct": 70.0,
                "trend_window": 10,
                "position": "F",
                "discrepancy_details": {
                    "best_bookmaker": "Betclic",
                    "lower_bookmaker": "Superbet",
                    "best_odds": 3.10,
                    "lower_odds": 1.88,
                    "odds_difference": 1.22,
                    "relative_price_difference_pct": 64.9,
                    "implied_probability_shift_pp": 20.94,
                },
            },
            {
                "canonical_prop_key": "kylian_mbappe_real_madrid_fc_barcelona_shots_3.5_over",
                "prop_type": "PLAYER",
                "player_name": "Kylian Mbappe",
                "team": "Real Madrid",
                "opponent": "Barcelona",
                "match_name": "Real Madrid vs Barcelona",
                "competition": "La Liga",
                "stat_type": "SHOTS",
                "line": 3.5,
                "side": "OVER",
                "best_bookmaker": "betclic",
                "best_raw_odds": 4.50,
                "lower_executable_bookmaker": "superbet",
                "lower_executable_odds": 2.00,
                "superbet_odds": 2.00,
                "betclic_odds": 4.50,
                "odds_difference": 2.50,
                "relative_price_difference_pct": 125.0,
                "is_discrepancy": True,
                "status": "QUALIFIED",
                "is_valuebet": True,
                "net_ev_pct": 5.8,
                "hit_rate_pct": 60.0,
                "trend_window": 10,
                "position": "F",
                "discrepancy_details": {
                    "best_bookmaker": "Betclic",
                    "lower_bookmaker": "Superbet",
                    "best_odds": 4.50,
                    "lower_odds": 2.00,
                    "odds_difference": 2.50,
                    "relative_price_difference_pct": 125.0,
                    "implied_probability_shift_pp": 27.78,
                },
            },
            {
                "canonical_prop_key": "rodri_manchester_city_arsenal_fouls_1.5_over",
                "prop_type": "PLAYER",
                "player_name": "Rodri",
                "team": "Manchester City",
                "opponent": "Arsenal",
                "match_name": "Manchester City vs Arsenal",
                "competition": "Premier League",
                "stat_type": "FOULS",
                "line": 1.5,
                "side": "OVER",
                "best_bookmaker": "superbet",
                "best_raw_odds": 2.00,
                "lower_executable_bookmaker": "betclic",
                "lower_executable_odds": 1.50,
                "superbet_odds": 2.00,
                "betclic_odds": 1.50,
                "odds_difference": 0.50,
                "relative_price_difference_pct": 33.3,
                "is_discrepancy": True,
                "status": "QUALIFIED",
                "is_valuebet": True,
                "net_ev_pct": 7.2,
                "hit_rate_pct": 80.0,
                "trend_window": 10,
                "position": "M",
                "discrepancy_details": {
                    "best_bookmaker": "Superbet",
                    "lower_bookmaker": "Betclic",
                    "best_odds": 2.00,
                    "lower_odds": 1.50,
                    "odds_difference": 0.50,
                    "relative_price_difference_pct": 33.3,
                    "implied_probability_shift_pp": 16.67,
                },
            },
            {
                "canonical_prop_key": "erling_haaland_manchester_city_arsenal_shots_on_target_1.5_over",
                "prop_type": "PLAYER",
                "player_name": "Erling Haaland",
                "team": "Manchester City",
                "opponent": "Arsenal",
                "match_name": "Manchester City vs Arsenal",
                "competition": "Premier League",
                "stat_type": "SHOTS_ON_TARGET",
                "line": 1.5,
                "side": "OVER",
                "best_bookmaker": "betclic",
                "best_raw_odds": 2.25,
                "lower_executable_bookmaker": "superbet",
                "lower_executable_odds": 1.85,
                "superbet_odds": 1.85,
                "betclic_odds": 2.25,
                "odds_difference": 0.40,
                "relative_price_difference_pct": 21.6,
                "is_discrepancy": True,
                "status": "QUALIFIED",
                "is_valuebet": True,
                "net_ev_pct": 8.4,
                "hit_rate_pct": 75.0,
                "trend_window": 10,
                "position": "F",
                "discrepancy_details": {
                    "best_bookmaker": "Betclic",
                    "lower_bookmaker": "Superbet",
                    "best_odds": 2.25,
                    "lower_odds": 1.85,
                    "odds_difference": 0.40,
                    "relative_price_difference_pct": 21.6,
                    "implied_probability_shift_pp": 9.6,
                },
            },
            {
                "canonical_prop_key": "arsenal_manchester_city_corners_4.5_over",
                "prop_type": "TEAM",
                "player_name": "Arsenal",
                "team": "Arsenal",
                "opponent": "Manchester City",
                "match_name": "Manchester City vs Arsenal",
                "competition": "Premier League",
                "stat_type": "CORNERS",
                "line": 4.5,
                "side": "OVER",
                "best_bookmaker": "superbet",
                "best_raw_odds": 2.10,
                "lower_executable_bookmaker": "betclic",
                "lower_executable_odds": 1.75,
                "superbet_odds": 2.10,
                "betclic_odds": 1.75,
                "odds_difference": 0.35,
                "relative_price_difference_pct": 20.0,
                "is_discrepancy": True,
                "status": "QUALIFIED",
                "is_valuebet": True,
                "net_ev_pct": 6.9,
                "hit_rate_pct": 70.0,
                "trend_window": 10,
                "discrepancy_details": {
                    "best_bookmaker": "Superbet",
                    "lower_bookmaker": "Betclic",
                    "best_odds": 2.10,
                    "lower_odds": 1.75,
                    "odds_difference": 0.35,
                    "relative_price_difference_pct": 20.0,
                    "implied_probability_shift_pp": 9.5,
                },
            },
            {
                "canonical_prop_key": "jude_bellingham_real_madrid_barcelona_fouls_2.5_over",
                "prop_type": "PLAYER",
                "player_name": "Jude Bellingham",
                "team": "Real Madrid",
                "opponent": "Barcelona",
                "match_name": "Real Madrid vs Barcelona",
                "competition": "La Liga",
                "stat_type": "FOULS",
                "line": 2.5,
                "side": "OVER",
                "best_bookmaker": "superbet",
                "best_raw_odds": 2.45,
                "lower_executable_bookmaker": "betclic",
                "lower_executable_odds": 2.10,
                "superbet_odds": 2.45,
                "betclic_odds": 2.10,
                "odds_difference": 0.35,
                "relative_price_difference_pct": 16.7,
                "is_discrepancy": True,
                "status": "QUALIFIED",
                "is_valuebet": True,
                "net_ev_pct": 9.2,
                "hit_rate_pct": 80.0,
                "trend_window": 10,
                "position": "M",
                "discrepancy_details": {
                    "best_bookmaker": "Superbet",
                    "lower_bookmaker": "Betclic",
                    "best_odds": 2.45,
                    "lower_odds": 2.10,
                    "odds_difference": 0.35,
                    "relative_price_difference_pct": 16.7,
                    "implied_probability_shift_pp": 6.8,
                },
            },
            {
                "canonical_prop_key": "lautaro_martinez_inter_milan_juventus_shots_on_target_1.5_over",
                "prop_type": "PLAYER",
                "player_name": "Lautaro Martinez",
                "team": "Inter Milan",
                "opponent": "Juventus",
                "match_name": "Inter Milan vs Juventus",
                "competition": "Serie A",
                "stat_type": "SHOTS_ON_TARGET",
                "line": 1.5,
                "side": "OVER",
                "best_bookmaker": "betclic",
                "best_raw_odds": 2.30,
                "lower_executable_bookmaker": "superbet",
                "lower_executable_odds": 1.90,
                "superbet_odds": 1.90,
                "betclic_odds": 2.30,
                "odds_difference": 0.40,
                "relative_price_difference_pct": 21.1,
                "is_discrepancy": True,
                "status": "QUALIFIED",
                "is_valuebet": True,
                "net_ev_pct": 7.5,
                "hit_rate_pct": 65.0,
                "trend_window": 10,
                "position": "F",
                "discrepancy_details": {
                    "best_bookmaker": "Betclic",
                    "lower_bookmaker": "Superbet",
                    "best_odds": 2.30,
                    "lower_odds": 1.90,
                    "odds_difference": 0.40,
                    "relative_price_difference_pct": 21.1,
                    "implied_probability_shift_pp": 9.1,
                },
            },
        ]
        PlatformAPIService._cached_global_props_ultra_results = {
            "status": "SUCCESS",
            "scan_mode": "ULTRA",
            "scope": {"scan_mode": "ULTRA", "props_scope": "ALL", "max_results": 50},
            "budget": {"max_fixtures": 60, "max_trends_requests": 60, "max_execution_events": 60},
            "funnel_metrics": {
                "scan_mode": "ULTRA",
                "fixtures_discovered": 52,
                "fixtures_selected": 48,
                "pages_requested": 12,
                "pages_successful": 12,
                "pages_failed": 0,
                "trends_discovered": 164,
                "trends_deduplicated": 82,
                "player_props_evaluated": 64,
                "team_props_evaluated": 18,
                "matched_both_bookmakers": 7,
                "quote_discrepancies": 7,
                "valuebets_qualified": 6,
                "rejection_breakdown": {
                    "BELOW_VALUE_THRESHOLD": 40,
                    "POLISH_ODDS_UNAVAILABLE": 22,
                    "INSUFFICIENT_REFERENCE_SOURCES": 12,
                },
            },
            "qualified_count": len(ultra_qualified),
            "diagnostic_count": 2,
            "qualified_opportunities": ultra_qualified,
            "diagnostic_candidates": PlatformAPIService._cached_global_props_results.get("diagnostic_candidates", []),
            "duration_ms": 14200.0,
        }

    loop.run_until_complete(server.serve())
