import os
import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
if "SQLITE_PATH" not in os.environ and "DATABASE_URL" not in os.environ:
    os.environ["SQLITE_PATH"] = "zielonebety.db"
    os.environ["DATABASE_URL"] = "sqlite:///zielonebety.db"

if sys.platform == "win32":
    import asyncio
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

import uvicorn
from api.fastapi_app import app


if __name__ == "__main__":
    print("Starting Uvicorn Server on 127.0.0.1:8000...", flush=True)
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    config = uvicorn.Config(app, host="127.0.0.1", port=8000, log_level="warning", loop="asyncio")
    server = uvicorn.Server(config)
    from api.services import PlatformAPIService
    if not PlatformAPIService._cached_global_props_results:
        PlatformAPIService._cached_global_props_results = {
            "status": "SUCCESS",
            "qualified_count": 4,
            "diagnostic_count": 2,
            "qualified_opportunities": [
                {
                    "canonical_prop_key": "vinicius_junior_real_madrid_fc_barcelona_shots_2.5_over",
                    "prop_type": "PLAYER",
                    "player_name": "Vinicius Junior",
                    "team": "Real Madrid",
                    "opponent": "Barcelona",
                    "match_name": "Real Madrid vs Barcelona",
                    "competition": "La Liga",
                    "stat_type": "SHOTS",
                    "line": 2.5,
                    "side": "OVER",
                    "best_bookmaker": "betclic",
                    "best_raw_odds": 3.10,
                    "lower_executable_bookmaker": "superbet",
                    "lower_executable_odds": 1.88,
                    "superbet_odds": 1.88,
                    "betclic_odds": 3.10,
                    "odds_difference": 1.22,
                    "relative_price_difference_pct": 64.9,
                    "is_discrepancy": True,
                    "status": "QUALIFIED",
                    "is_valuebet": False,
                    "net_ev_pct": None,
                    "hit_rate_pct": 70.0,
                    "trend_window": 10,
                    "position": "F",
                    "discrepancy_details": {
                        "best_bookmaker": "Betclic",
                        "lower_bookmaker": "Superbet",
                        "best_odds": 3.10,
                        "lower_odds": 1.88,
                        "odds_difference": 1.22,
                        "relative_price_difference_pct": 64.9,
                        "implied_probability_shift_pp": 20.94,
                    },
                },
                {
                    "canonical_prop_key": "kylian_mbappe_real_madrid_fc_barcelona_shots_3.5_over",
                    "prop_type": "PLAYER",
                    "player_name": "Kylian Mbappe",
                    "team": "Real Madrid",
                    "opponent": "Barcelona",
                    "match_name": "Real Madrid vs Barcelona",
                    "competition": "La Liga",
                    "stat_type": "SHOTS",
                    "line": 3.5,
                    "side": "OVER",
                    "best_bookmaker": "betclic",
                    "best_raw_odds": 4.50,
                    "lower_executable_bookmaker": "superbet",
                    "lower_executable_odds": 2.00,
                    "superbet_odds": 2.00,
                    "betclic_odds": 4.50,
                    "odds_difference": 2.50,
                    "relative_price_difference_pct": 125.0,
                    "is_discrepancy": True,
                    "status": "QUALIFIED",
                    "is_valuebet": True,
                    "net_ev_pct": 5.8,
                    "hit_rate_pct": 60.0,
                    "trend_window": 10,
                    "position": "F",
                    "discrepancy_details": {
                        "best_bookmaker": "Betclic",
                        "lower_bookmaker": "Superbet",
                        "best_odds": 4.50,
                        "lower_odds": 2.00,
                        "odds_difference": 2.50,
                        "relative_price_difference_pct": 125.0,
                        "implied_probability_shift_pp": 27.78,
                    },
                },
                {
                    "canonical_prop_key": "rodri_manchester_city_arsenal_fouls_1.5_over",
                    "prop_type": "PLAYER",
                    "player_name": "Rodri",
                    "team": "Manchester City",
                    "opponent": "Arsenal",
                    "match_name": "Manchester City vs Arsenal",
                    "competition": "Premier League",
                    "stat_type": "FOULS",
                    "line": 1.5,
                    "side": "OVER",
                    "best_bookmaker": "superbet",
                    "best_raw_odds": 2.00,
                    "lower_executable_bookmaker": "betclic",
                    "lower_executable_odds": 1.50,
                    "superbet_odds": 2.00,
                    "betclic_odds": 1.50,
                    "odds_difference": 0.50,
                    "relative_price_difference_pct": 33.3,
                    "is_discrepancy": True,
                    "status": "QUALIFIED",
                    "is_valuebet": True,
                    "net_ev_pct": 7.2,
                    "hit_rate_pct": 80.0,
                    "trend_window": 10,
                    "position": "M",
                    "discrepancy_details": {
                        "best_bookmaker": "Superbet",
                        "lower_bookmaker": "Betclic",
                        "best_odds": 2.00,
                        "lower_odds": 1.50,
                        "odds_difference": 0.50,
                        "relative_price_difference_pct": 33.3,
                        "implied_probability_shift_pp": 16.67,
                    },
                },
                {
                    "canonical_prop_key": "erling_haaland_manchester_city_arsenal_shots_2.5_over",
                    "prop_type": "PLAYER",
                    "player_name": "Erling Haaland",
                    "team": "Manchester City",
                    "opponent": "Arsenal",
                    "match_name": "Manchester City vs Arsenal",
                    "competition": "Premier League",
                    "stat_type": "SHOTS",
                    "line": 2.5,
                    "side": "OVER",
                    "best_bookmaker": "betclic",
                    "best_raw_odds": 2.00,
                    "lower_executable_bookmaker": "superbet",
                    "lower_executable_odds": 1.50,
                    "superbet_odds": 1.50,
                    "betclic_odds": 2.00,
                    "odds_difference": 0.50,
                    "relative_price_difference_pct": 33.3,
                    "is_discrepancy": True,
                    "status": "QUALIFIED",
                    "is_valuebet": False,
                    "net_ev_pct": None,
                    "hit_rate_pct": 75.0,
                    "trend_window": 10,
                    "position": "F",
                    "discrepancy_details": {
                        "best_bookmaker": "Betclic",
                        "lower_bookmaker": "Superbet",
                        "best_odds": 2.00,
                        "lower_odds": 1.50,
                        "odds_difference": 0.50,
                        "relative_price_difference_pct": 33.3,
                        "implied_probability_shift_pp": 16.67,
                    },
                },
            ],
            "diagnostic_candidates": [
                {
                    "canonical_prop_key": "real_madrid_fc_barcelona_corners_6.5_over",
                    "prop_type": "TEAM",
                    "player_name": "Real Madrid",
                    "team": "Real Madrid",
                    "opponent": "Barcelona",
                    "match_name": "Real Madrid vs Barcelona",
                    "competition": "La Liga",
                    "stat_type": "CORNERS",
                    "line": 6.5,
                    "side": "OVER",
                    "best_bookmaker": "superbet",
                    "best_raw_odds": 1.95,
                    "lower_executable_bookmaker": "betclic",
                    "lower_executable_odds": 1.90,
                    "superbet_odds": 1.95,
                    "betclic_odds": 1.90,
                    "odds_difference": 0.05,
                    "relative_price_difference_pct": 2.6,
                    "is_discrepancy": False,
                    "status": "BELOW_VALUE_THRESHOLD",
                    "is_valuebet": False,
                    "net_ev_pct": 0.5,
                    "hit_rate_pct": 55.0,
                    "trend_window": 10,
                },
                {
                    "canonical_prop_key": "robert_lewandowski_real_madrid_shots_2.5_over",
                    "prop_type": "PLAYER",
                    "player_name": "Robert Lewandowski",
                    "team": "Barcelona",
                    "opponent": "Real Madrid",
                    "match_name": "Real Madrid vs Barcelona",
                    "competition": "La Liga",
                    "stat_type": "SHOTS",
                    "line": 2.5,
                    "side": "OVER",
                    "best_bookmaker": "superbet",
                    "best_raw_odds": 1.80,
                    "lower_executable_bookmaker": None,
                    "lower_executable_odds": None,
                    "superbet_odds": 1.80,
                    "betclic_odds": None,
                    "odds_difference": None,
                    "relative_price_difference_pct": None,
                    "is_discrepancy": False,
                    "status": "POLISH_ODDS_UNAVAILABLE",
                    "is_valuebet": False,
                    "net_ev_pct": -1.0,
                    "hit_rate_pct": 60.0,
                    "trend_window": 10,
                    "position": "F",
                },
            ],
            "funnel_metrics": {},
        }
    loop.run_until_complete(server.serve())
