"""
Provider Base Framework Package
"""

from providers.base.provider_state import ProviderState
from providers.base.exceptions import (
    ProviderError,
    NonRetryableError,
    ProviderConfigurationError,
    ProviderInitializationError,
    ProviderStateError,
    ProviderRegistrationError,
    ProviderNotFoundError,
    ProviderDuplicateError,
    ProviderDisabledError,
    ScrapingError,
    SessionError,
    AuthenticationError,
    RateLimitError,
    ProxyError,
    BrowserError,
    BrowserLaunchError,
    BrowserCrashError,
    BrowserPoolExhaustedError,
    PageError,
    PageCrashError,
    NavigationError,
    NavigationTimeoutError,
    ExtractionError,
    NetworkExtractionError,
    JsonExtractionError,
    DomExtractionError,
    EmptyResponseError,
    RetryExhaustedError,
    ProviderTimeoutError,
)
from providers.base.models import (
    ProviderMetadata,
    ValidationReport,
    ProviderMetrics,
    QualityReport,
    QualityStatus,
    HealthSnapshot,
    FrameworkHealthReport,
    DiagnosticsBundle,
    DiagnosticsReport,
    ExtractionStrategy,
    TimeoutConfig,
    RetryConfig,
    RateLimitConfig,
    BrowserConfig,
    ProxyConfig,
)
from providers.base.provider_context import ProviderContext
from providers.base.provider_result import ProviderResult
from providers.base.provider_interface import ProviderInterface
from providers.base.base_provider import BaseProvider
from providers.base.provider_registry import ProviderRegistry
from providers.base.provider_factory import ProviderFactory
from providers.base.execution_engine import ExecutionEngine
from providers.base.provider_manager import ProviderManager, AggregatedExecutionResult
from providers.base.rate_limiter import RateLimiter
from providers.base.request_interceptor import RequestInterceptor, RequestInterceptorChain
from providers.base.response_interceptor import ResponseInterceptor, ResponseInterceptorChain
from providers.base.quality_report import QualityReportBuilder

__all__ = [
    "ProviderState",
    "ProviderError",
    "NonRetryableError",
    "ProviderConfigurationError",
    "ProviderInitializationError",
    "ProviderStateError",
    "ProviderRegistrationError",
    "ProviderNotFoundError",
    "ProviderDuplicateError",
    "ProviderDisabledError",
    "ScrapingError",
    "SessionError",
    "AuthenticationError",
    "RateLimitError",
    "ProxyError",
    "BrowserError",
    "BrowserLaunchError",
    "BrowserCrashError",
    "BrowserPoolExhaustedError",
    "PageError",
    "PageCrashError",
    "NavigationError",
    "NavigationTimeoutError",
    "ExtractionError",
    "NetworkExtractionError",
    "JsonExtractionError",
    "DomExtractionError",
    "EmptyResponseError",
    "RetryExhaustedError",
    "ProviderTimeoutError",
    "ProviderMetadata",
    "ValidationReport",
    "ProviderMetrics",
    "QualityReport",
    "QualityStatus",
    "HealthSnapshot",
    "FrameworkHealthReport",
    "DiagnosticsBundle",
    "DiagnosticsReport",
    "ExtractionStrategy",
    "TimeoutConfig",
    "RetryConfig",
    "RateLimitConfig",
    "BrowserConfig",
    "ProxyConfig",
    "ProviderContext",
    "ProviderResult",
    "ProviderInterface",
    "BaseProvider",
    "ProviderRegistry",
    "ProviderFactory",
    "ExecutionEngine",
    "ProviderManager",
    "AggregatedExecutionResult",
    "RateLimiter",
    "RequestInterceptor",
    "RequestInterceptorChain",
    "ResponseInterceptor",
    "ResponseInterceptorChain",
    "QualityReportBuilder",
]
